backend/images/.gitignore, backend/package-lock.json, backend/package.json, backend/server.js, backend/upload.js
An uploading endpoint that uses `multer` to handle file uploads.
This PR is to make sure that this endpoint makes sense for the ideas that Bill/Tina have about image uploading.
=> Adding an image uploading endpoint

frontend/src/Student/components/SubmissionFormChooser.js, frontend/src/Student/pages/Dashboard.js
~~~Brings in font-awesome as a dependency.~~~
old:
new:
=> stylize form submission type chooser

frontend/src/Student/components/Layout.js, frontend/src/Student/components/NavBar.js, frontend/src/Student/containers/NavBar.js
=> Add navbar to the student dashboard

backend/config/auth.js, backend/helpers/jwt.js, backend/middleware/parseJwtUser.js, backend/routes/auth.js, backend/routes/download.js, backend/test/routes/auth.js, backend/test/routes/zipDownload.js
Adds a download token, also refactors token signing and parsing into a helper module. Includes tests of functionality.
=> add download token

frontend/package.json, frontend/src/Admin/components/AssignJudgesTable.js, frontend/src/Admin/components/CreateShowForm.js, frontend/src/Admin/components/ShowCard.js, frontend/src/Admin/pages/CreateShow.js, frontend/src/Admin/pages/Dashboard.js, frontend/src/Home/Page.js, frontend/src/index.js, frontend/yarn.lock
Removes Rebass.
Also restructures how the home page scales, hiding the accent image on `xs` screens and fixing the ever-present horizontal scrollbar.
Also tweaks how buttons look on the Show card (sorry, couldn't help myself)
Album of changes: https://imgur.com/a/2vd1w 
Closes #155
Closes #130 (Duplicate PR)
=> Remove Rebass from the project

backend/resolvers/mutations/vote.js, backend/test/resolvers/vote.js, frontend/src/Admin/components/NavBar.js, frontend/src/Admin/containers/NavBar.js, frontend/src/Judge/components/NavBar.js, frontend/src/Judge/containers/NavBar.js, frontend/src/shared/actions.js, frontend/src/shared/components/LoginSwitch.js, frontend/src/shared/reducers.js
In this PR I added actions/reducers to toggle judge/admin roles and produce the admin or judge view based on the active performing role.
I also realized a bug with the way I wrote voting (admins need to vote too). So that's fixed an tested.
=> Toggle between admin and judge role

backend/models/entry.js, backend/models/show.js, backend/models/user.js, backend/models/vote.js, backend/resolvers/index.js, backend/resolvers/mutations/entry.js, backend/resolvers/queries/entryQuery.js, backend/resolvers/queries/showQuery.js, backend/resolvers/types/entryType.js, backend/resolvers/types/otherMediaType.js, backend/resolvers/types/photoType.js, backend/resolvers/types/showType.js, backend/resolvers/types/videoType.js, backend/schema.js, backend/test/resolvers/entry.js, backend/test/resolvers/entryQuery.js, backend/test/resolvers/showQuery.js, backend/test/util.js
To handle the issues described in #164 I modified two queries: shows and entries.
Both queries now have an optional studentUsername param. The entries query solves the first comment's problem. And the shows query solves the wishlist comment's problem.
=> Allowing students to get their own entries by searching entries or searching shows

backend/resolvers/types/entryType.js, backend/schema.js, backend/test/resolvers/entryQuery.js
Feature request from slack's #discussion
=> Surfacing entry type on entry

backend/server.js, frontend/src/Student/components/ShowCard.js, frontend/src/Student/queries/shows.graphql
Adds icons (youtube, vimeo, other ...) and thumbnails (photos) on a student's dashboard to show them what they have submitted.
I'm not sure what to do with the new submission button, for now it's centered in whatever space remains on the current row.
Youtube and Vimeo submissions are links to their videos. Other submissions just render the book icon, although I _suppose_ we could include their jpeg if included.
Gallery for changes: https://imgur.com/a/ozZIk
We might also want to make the submission title truncated into ellipsis if it's really long.
=> Add small icons & thumnails for submitted entries

backend/test/factories.js, backend/test/resolvers/entryQuery.js, backend/test/resolvers/voteQuery.js, backend/test/routes/zipDownload.js
fixes multiple asynchronous oddities that caused some tests to fail intermittently
=> make tests repeatable again

frontend/src/Judge/components/VotePanel.js
=> Add Keyboard Controls to Voting Panel

frontend/package.json, frontend/src/Judge/actions.js, frontend/src/Judge/pages/Vote.js, frontend/src/Judge/reducers.js, frontend/yarn.lock
Adds refreshable URLs. This is accomplished by removing the 'viewing' property from state and instead relying on conneccted-react-router's state.
=> make judging urls refreshable

frontend/package.json, frontend/src/Judge/actions.js, frontend/src/Judge/components/NavBar.js, frontend/src/Judge/components/OtherMediaSubmission.js, frontend/src/Judge/components/PhotoSubmission.js, frontend/src/Judge/components/Submission.js, frontend/src/Judge/components/VideoSubmission.js, frontend/src/Judge/components/VotePanel.js, frontend/src/Judge/containers/VotePanel.js, frontend/src/Judge/pages/Dashboard.js, frontend/src/Judge/pages/Vote.js, frontend/yarn.lock
This PR add the ability to view photos on the judging page. They are rendered to max fit in the voting container without stretching. When clicked on a "lightbox" feature is rendered. This renders the image max size for the entire window.
I also changed the video rendering to fill the component
Examples:
=> Adding Photo voting view

backend/resolvers/queries/showQuery.js
Modifies the Shows query to show all Shows to which the student has submitted, plus all open shows.
Fixes #226
=> allow students to query open show calls

frontend/src/Admin/actions.js, frontend/src/Admin/components/ShowDetailsTab.js, frontend/src/Admin/containers/ShowDetailsTab.js, frontend/src/Admin/pages/ViewShow.js, frontend/src/shared/actions.js, frontend/src/shared/reducers.js
~DO NOT MERGE~ OK to merge
adds a 'download zip' button, plus other (currently useless) buttons for reports, addresses #214
=> Add download button

backend/resolvers/types/entryType.js, backend/schema.js, frontend/src/Admin/components/ShowJudgesTab.js, frontend/src/Admin/containers/ShowJudgesTab.js, frontend/src/Admin/pages/ViewShow.js, frontend/src/Admin/queries/show.graphql, frontend/src/Judge/pages/Vote.js, frontend/src/Student/components/OtherMediaSubmissionForm.js, frontend/src/Student/components/PhotoSubmissionForm.js, frontend/src/Student/components/VideoSubmissionForm.js
Adds loading-bars which indicate judging progress. See below for photos.
Adds a backend change to add property on entries called 'votes' which exposes all votes made on that entry.
=> Add judge progress loading-bars

frontend/src/Admin/components/ShowSubmissionDetails.js, frontend/src/Admin/components/ShowSubmissionsTab.js, frontend/src/Admin/queries/show.graphql
=> Submission More Details Modal

frontend/src/Admin/actions.js, frontend/src/Admin/components/ShowSubmissionDetails.js, frontend/src/Admin/containers/NavBar.js, frontend/src/Admin/containers/ShowDetailsTab.js, frontend/src/shared/actions.js, frontend/src/utils/index.js
=> Download Single Image Button

frontend/src/Admin/components/AssignJudgesTable.js, frontend/src/Admin/components/CreateJudgeForm.js, frontend/src/Admin/components/CreateShowForm.js, frontend/src/Admin/components/NavBar.js, frontend/src/Admin/components/ShowCard.js, frontend/src/Admin/components/ShowDetailsTab.js, frontend/src/Admin/components/ShowSubmissionDetails.js, frontend/src/Admin/components/ShowSubmissionsTab.js, frontend/src/Admin/pages/AssignJudges.js, frontend/src/Admin/pages/ManageJudges.js, frontend/src/Judge/components/ShowCard.js, frontend/src/Judge/containers/NavBar.js, frontend/src/Judge/pages/Vote.js, frontend/src/Student/components/OtherMediaSubmissionForm.js, frontend/src/Student/components/PhotoSubmissionForm.js, frontend/src/Student/components/ShowCard.js, frontend/src/Student/components/VideoSubmissionForm.js, frontend/src/Student/containers/NavBar.js, frontend/src/shared/actions.js
Updates the Visual Design:
- Admin Show Card
- Admin Show Details Tab
- Judge Show Card
=> Frontend Polish

backend/db/migrations/20180424235800-make-user-shows-cascade.js
Makes user_shows cascade-delete
=> make user_shows cascade on delete

frontend/package.json, frontend/src/Admin/pages/PrintableReport.js, frontend/yarn.lock
"show" was not defined until after the app mounted,
so the app would crash when trying to set the page title.
It now uses a tool specifically made for setting the page title.
Note, having `<Fragment>` be a child of `<DocumentTitle>` is intentional. `<DocumentTitle>` expects to only have one child component.
I also added in propTypes for this component.
=> Fix Printable Report Title Bug

frontend/src/Admin/components/NavBar.js, frontend/src/Judge/components/NavBar.js
Looks like this, pipe does not change to white on mouse over
=> fix vertical separator in navbar being in link

backend/.eslintrc.js, backend/bin/www.js, backend/config/database.js, backend/config/index.js, backend/middleware/parseJwtUser.js, backend/models/image.js, backend/models/other.js, backend/models/video.js, backend/routes/upload.js, backend/schema.js, backend/server.js, frontend/src/Admin/components/ShowDetailsTab.js, frontend/src/Student/components/PhotoSubmissionForm.js, frontend/src/shared/actions.js, frontend/src/shared/components/LoginSwitch.js
- Don't show Sequelize warnings
- Update Sequelize Models to v4
- Removing unused code & Adding comments
- Update some outstanding frontend error handling
- Disable X-Powered-By Header
- Disable CORS in production
The only thing I'm not 100% on is the CORS change. Because we serve the frontend and backend on the same domain, `gallerygateway.rit.edu`, I don't think we need CORS enabled, but I may be wrong. We would need it for local dev because they're run on different ports.
=> Code Cleanup & Backend Security Best Practices
